import { clinicalApi } from '../services/api.js';
import { mountScreen, renderError, showToast, queryParam, toneForStatus, monthRange } from '../shared/screen.js';
import { escapeHtml, formatDateTime, formatDate, formatMoney } from '../utils/html.js';
import { loading, empty, badge } from '../components/ui.js';
const root=mountScreen({key:'alergias-alertas',title:'Alergias e alertas',roles:["MEDICO"]});
if(root){void init();}
async function init(){try{
  
  const id=queryParam('patientId');const load=async()=>{const s=await clinicalApi.snapshot(id);root.innerHTML=`<div class="two-columns"><form id="allergy" class="panel form-grid"><h2>Nova alergia</h2><label>Substância<input name="substance" required></label><label>Reação<input name="reaction"></label><label>Severidade<select name="severity"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><button class="primary-button">Registrar</button></form><form id="alert" class="panel form-grid"><h2>Novo alerta</h2><label>Tipo<input name="type" required></label><label>Severidade<select name="severity"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label>Mensagem<input name="message" required></label><button class="primary-button">Registrar</button></form></div><article class="panel"><h2>Alertas ativos</h2>${(s.alerts||[]).map(a=>`<div class="alert"><strong>${escapeHtml(a.type)}</strong> — ${escapeHtml(a.severity)} <button class="ghost-button" data-off="${a.id}">Desativar</button></div>`).join('')||'<p>Nenhum.</p>'}</article>`;root.querySelector('#allergy').addEventListener('submit',async e=>{e.preventDefault();await clinicalApi.addAllergy(id,Object.fromEntries(new FormData(e.currentTarget).entries()));await load();});root.querySelector('#alert').addEventListener('submit',async e=>{e.preventDefault();await clinicalApi.addAlert(id,Object.fromEntries(new FormData(e.currentTarget).entries()));await load();});root.querySelectorAll('[data-off]').forEach(b=>b.addEventListener('click',async()=>{await clinicalApi.deactivateAlert(id,b.dataset.off);await load();}));};await load();
}catch(error){renderError(root,error);}}
